CC=g++
Vector:
	$(CC) -o Vector vectorMain.cpp funkcijos.cpp
Deque: 
	$(CC) -o Deque DeQueMain.cpp Dequefunkcijos.cpp
List:
	$(CC) -o List listMain.cpp Listfunkcijos.cpp
GenerateFile:
	$(CC) -o GenerateFile SarasoGen.cpp
clean:
	rm *. *.txt
